### ISSUE TITLE
Include dataset

### ISSUE THREAD

**Issue by HadleRS** [intangere/cIon#1]
Is it possible to include the example movie dialogue dataset, so that I can test your code?

**Comment by intangere** [comment]
Sure. I'll add it.

**Comment by HadleRS** [comment]
Thanks!
Im getting this error when trying to run it, any idea why?
Traceback (most recent call last):
  File "model.py", line 24, in <module>
    import seq2seq_model
  File "/home/ubuntu/cIon/seq2seq_model.py", line 29, in <module>
    from tensorflow.models.rnn.translate import data_utils
ImportError: No module named translate

**Comment by intangere** [comment]
Fixed it. A module was renamed and I forgot to push it.
